import authController from './auth';
import requestController from './request';
import profileController from './profile';
import likeController from './like';
import notificationController from './notification';
import commentController from './comment';
import accommodationController from './accommodation';
import roomController from './room';
import tripController from './trips';
import ratingController from './rating';

export const AuthController = authController;
export const ProfileController = profileController;
export const RequestController = requestController;
export const CommentController = commentController;
export const AccommodationController = accommodationController;
export const LikeController = likeController;
export const NotificationController = notificationController;
export const RoomController = roomController;
export const TripController = tripController;
export const RatingController = ratingController;
